<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NicheSeeder extends Seeder
{
    public function run(): void
    {
        $niches = [
            'Plumbing Service', 'Emergency Plumber', 'AC Repair', 'Heating & Furnace Repair',
            'HVAC Installation', 'Roofing Contractors', 'Electricians', 'Solar Panel Installers',
            'Handyman Services', 'Home Renovation', 'Kitchen Remodeling', 'Bathroom Remodeling',
            'Flooring Contractors', 'Tile Installation', 'Carpet Cleaning', 'Upholstery Cleaning',
            'Window Cleaning', 'House Cleaning', 'Maid Services', 'Pest Control', 'Exterminators',
            'Termite Treatment', 'Landscaping', 'Lawn Care', 'Tree Removal', 'Tree Trimming',
            'Pool Cleaning', 'Pool Repair', 'Water Damage Restoration', 'Fire Damage Restoration',
            'Mold Removal', 'Home Security Installation', 'Locksmiths', 'Garage Door Repair',
            'Fencing Installation', 'Driveway Paving', 'Concrete Contractors', 'Foundation Repair',
            'Moving Companies', 'Junk Removal', 'Dumpster Rental', 'Gutter Cleaning',
            'Pressure Washing', 'Septic Tank Cleaning', 'Excavation Contractors',
            'Roofing Inspectors', 'Skylight Installation', 'Insulation Contractors',
            'Painters (Interior/Exterior)', 'Wallpaper Installers', 'Limo Services', 'Airport Limo',
            'Chauffeur Service', 'Party Bus Rentals', 'Taxi Services', 'Car Rental Agencies',
            'Motorcycle Rental', 'RV Rental', 'Towing Services', 'Emergency Roadside Assistance',
            'Auto Glass Repair', 'Auto Body Shops', 'Car Detailing', 'Car Wash Services',
            'Transmission Repair', 'Brake Repair', 'Oil Change Shops', 'Tire Shops',
            'Car Dealerships', 'Used Car Dealers', 'Driving Schools', 'Motorcycle Repair',
            'Boat Rental', 'Yacht Charters', 'Parking Services', 'Shuttle Services',
            'Courier Services', 'Dentists', 'Cosmetic Dentists', 'Orthodontists',
            'Pediatric Dentists', 'Dermatologists', 'Chiropractors', 'Physiotherapists',
            'Family Doctors', 'Urgent Care Clinics', 'Pediatricians', 'Eye Doctors',
            'Optometrists', 'Ophthalmologists', 'LASIK Clinics', 'Psychologists', 'Psychiatrists',
            'Counselors', 'Speech Therapists', 'Nutritionists', 'Weight Loss Clinics',
            'Plastic Surgeons', 'Hair Transplant Clinics', 'Fertility Clinics', 'Midwives',
            'Home Healthcare', 'Nursing Services', 'Elderly Care Homes', 'Massage Therapists',
            'Acupuncture Clinics', 'Naturopaths', 'Veterinary Clinics', 'Pet Groomers',
            'Animal Boarding', 'Personal Injury Lawyers', 'Family Lawyers', 'Divorce Lawyers',
            'Criminal Defense Attorneys', 'Real Estate Lawyers', 'Immigration Lawyers',
            'Business Lawyers', 'Employment Lawyers', 'Tax Lawyers', 'Bankruptcy Lawyers',
            'Insurance Lawyers', 'IP/Trademark Lawyers', 'Notary Public Services',
            'Financial Advisors', 'Accountants', 'Bookkeepers', 'Tax Preparers',
            'Mortgage Brokers', 'Loan Officers', 'Insurance Agents', 'Real Estate Appraisers',
            'Bail Bond Services', 'Restaurants', 'Pizza Delivery', 'Coffee Shops', 'Bakeries',
            'Catering Companies', 'Meal Prep Services', 'Juice Bars', 'Ice Cream Shops',
            'Bars & Nightclubs', 'Food Trucks', 'Wedding Caterers', 'Banquet Halls',
            'Event Venues', 'Hotels', 'Motels', 'Bed & Breakfasts', 'Resorts',
            'Airbnb Property Managers', 'Hostels', 'Travel Agencies', 'Tour Guides',
            'Wedding Photographers', 'Videographers', 'DJs', 'Makeup Artists', 'Hair Stylists',
            'Wedding Planners', 'Event Planners', 'Party Rentals', 'Bounce House Rentals',
            'Tent Rentals', 'Lighting & Audio Rentals', 'Birthday Party Planners',
            'Baby Shower Planners', 'Florists', 'Balloon Decorators', 'Tattoo Shops',
            'Piercing Shops', 'Gyms', 'Personal Trainers', 'Yoga Studios', 'Dance Studios',
            'Martial Arts Schools', 'Swimming Schools', 'Music Teachers', 'Language Tutors',
            'Babysitters', 'Nannies', 'Pet Sitters', 'Printing Services',
            'Digital Marketing Agencies', 'Web Designers', 'IT Support Services',
            'Security Guard Services', 'Courier Companies', 'Freight Forwarders',
            'Logistics Companies', 'Warehousing', 'Cleaning Contractors', 'Janitorial Services',
            'Staffing Agencies', 'Recruitment Agencies', 'Call Centers', 'Commercial Movers',
            'Waste Disposal', 'Hazardous Material Disposal', 'Solar Panel Contractors',
            'Commercial Roofing', 'Industrial Painters', 'Factory Equipment Repair',
            'Welding Services', 'CNC Machining', 'Private Tutors', 'Test Prep Centers',
            'Driving Schools', 'Coding Bootcamps', 'Language Institutes', 'Music Schools',
            'Dance Academies', 'Martial Arts Schools', 'Art Schools', 'Cooking Classes',
            'Daycares', 'Preschools', 'Montessori Schools', 'After-School Programs',
            'Summer Camps', 'College Consultants', 'Career Coaches', 'Public Speaking Trainers',
            'Plumbing Service Services', 'Emergency Plumber Services', 'AC Repair Services',
            'Heating & Furnace Repair Services', 'HVAC Installation Services',
            'Roofing Contractors Services', 'Electricians Services',
            'Solar Panel Installers Services', 'Handyman Services Services',
            'Home Renovation Services', 'Kitchen Remodeling Services',
            'Bathroom Remodeling Services', 'Flooring Contractors Services',
            'Tile Installation Services', 'Carpet Cleaning Services',
            'Upholstery Cleaning Services', 'Window Cleaning Services',
            'House Cleaning Services', 'Maid Services Services', 'Pest Control Services',
            'Exterminators Services', 'Termite Treatment Services', 'Landscaping Services',
            'Lawn Care Services', 'Tree Removal Services', 'Tree Trimming Services',
            'Pool Cleaning Services', 'Pool Repair Services',
            'Water Damage Restoration Services', 'Fire Damage Restoration Services',
            'Mold Removal Services', 'Home Security Installation Services',
            'Locksmiths Services', 'Garage Door Repair Services',
            'Fencing Installation Services', 'Driveway Paving Services',
            'Concrete Contractors Services', 'Foundation Repair Services',
            'Moving Companies Services', 'Junk Removal Services', 'Dumpster Rental Services',
            'Gutter Cleaning Services', 'Pressure Washing Services',
            'Septic Tank Cleaning Services', 'Excavation Contractors Services',
            'Roofing Inspectors Services', 'Skylight Installation Services',
            'Insulation Contractors Services', 'Painters (Interior/Exterior) Services',
            'Wallpaper Installers Services', 'Limo Services Services', 'Airport Limo Services',
            'Chauffeur Service Services', 'Party Bus Rentals Services', 'Taxi Services Services',
            'Car Rental Agencies Services', 'Motorcycle Rental Services', 'RV Rental Services',
            'Towing Services Services', 'Emergency Roadside Assistance Services',
            'Auto Glass Repair Services', 'Auto Body Shops Services', 'Car Detailing Services',
            'Car Wash Services Services', 'Transmission Repair Services',
            'Brake Repair Services', 'Oil Change Shops Services', 'Tire Shops Services',
            'Car Dealerships Services', 'Used Car Dealers Services', 'Driving Schools Services',
            'Motorcycle Repair Services', 'Boat Rental Services', 'Yacht Charters Services',
            'Parking Services Services', 'Shuttle Services Services', 'Courier Services Services',
            'Dentists Services', 'Cosmetic Dentists Services', 'Orthodontists Services',
            'Pediatric Dentists Services', 'Dermatologists Services', 'Chiropractors Services',
            'Physiotherapists Services', 'Family Doctors Services',
            'Urgent Care Clinics Services', 'Pediatricians Services', 'Eye Doctors Services',
            'Optometrists Services', 'Ophthalmologists Services', 'LASIK Clinics Services',
            'Psychologists Services', 'Psychiatrists Services', 'Counselors Services',
            'Speech Therapists Services', 'Nutritionists Services',
            'Weight Loss Clinics Services', 'Plastic Surgeons Services',
            'Hair Transplant Clinics Services', 'Fertility Clinics Services',
            'Midwives Services', 'Home Healthcare Services', 'Nursing Services Services',
            'Elderly Care Homes Services', 'Massage Therapists Services',
            'Acupuncture Clinics Services', 'Naturopaths Services',
            'Veterinary Clinics Services', 'Pet Groomers Services', 'Animal Boarding Services',
            'Personal Injury Lawyers Services', 'Family Lawyers Services',
            'Divorce Lawyers Services', 'Criminal Defense Attorneys Services',
            'Real Estate Lawyers Services', 'Immigration Lawyers Services',
            'Business Lawyers Services', 'Employment Lawyers Services',
            'Tax Lawyers Services', 'Bankruptcy Lawyers Services',
            'Insurance Lawyers Services', 'IP/Trademark Lawyers Services',
            'Notary Public Services Services', 'Financial Advisors Services',
            'Accountants Services', 'Bookkeepers Services', 'Tax Preparers Services',
            'Mortgage Brokers Services', 'Loan Officers Services', 'Insurance Agents Services',
            'Real Estate Appraisers Services', 'Bail Bond Services Services',
            'Restaurants Services', 'Pizza Delivery Services', 'Coffee Shops Services',
            'Bakeries Services', 'Catering Companies Services', 'Meal Prep Services Services',
            'Juice Bars Services', 'Ice Cream Shops Services', 'Bars & Nightclubs Services',
            'Food Trucks Services', 'Wedding Caterers Services', 'Banquet Halls Services',
            'Event Venues Services', 'Hotels Services', 'Motels Services',
            'Bed & Breakfasts Services', 'Resorts Services',
            'Airbnb Property Managers Services', 'Hostels Services',
            'Travel Agencies Services', 'Tour Guides Services',
            'Wedding Photographers Services', 'Videographers Services', 'DJs Services',
            'Makeup Artists Services', 'Hair Stylists Services', 'Wedding Planners Services',
            'Event Planners Services', 'Party Rentals Services',
            'Bounce House Rentals Services', 'Tent Rentals Services',
            'Lighting & Audio Rentals Services', 'Birthday Party Planners Services',
            'Baby Shower Planners Services', 'Florists Services', 'Balloon Decorators Services',
            'Tattoo Shops Services', 'Piercing Shops Services', 'Gyms Services',
            'Personal Trainers Services', 'Yoga Studios Services', 'Dance Studios Services',
            'Martial Arts Schools Services', 'Swimming Schools Services',
            'Music Teachers Services', 'Language Tutors Services', 'Babysitters Services',
            'Nannies Services', 'Pet Sitters Services', 'Printing Services Services',
            'Digital Marketing Agencies Services', 'Web Designers Services',
            'IT Support Services Services', 'Security Guard Services Services',
            'Courier Companies Services', 'Freight Forwarders Services',
            'Logistics Companies Services', 'Warehousing Services',
            'Cleaning Contractors Services', 'Janitorial Services Services',
            'Staffing Agencies Services', 'Recruitment Agencies Services',
            'Call Centers Services', 'Commercial Movers Services', 'Waste Disposal Services',
            'Hazardous Material Disposal Services', 'Solar Panel Contractors Services',
            'Commercial Roofing Services', 'Industrial Painters Services',
            'Factory Equipment Repair Services', 'Welding Services Services',
            'CNC Machining Services', 'Private Tutors Services', 'Test Prep Centers Services',
            'Driving Schools Services', 'Coding Bootcamps Services',
            'Language Institutes Services', 'Music Schools Services',
            'Dance Academies Services', 'Martial Arts Schools Services',
            'Art Schools Services', 'Cooking Classes Services', 'Daycares Services',
            'Preschools Services', 'Montessori Schools Services',
            'After-School Programs Services', 'Summer Camps Services',
            'College Consultants Services', 'Career Coaches Services',
            'Public Speaking Trainers Services',
        ];

        DB::table('niches')->truncate();

        $rows = array_map(fn($name) => ['name' => $name], $niches);

        foreach (array_chunk($rows, 100) as $chunk) {
            DB::table('niches')->insert($chunk);
        }
    }
}
